export type QuizCentreQuestion = {
  q: string;
  opts: string[];
  ans: number;
  exp: string;
};

export type QuizCentreQuiz = {
  id: number;
  title: string;
  category: string;
  color: string;
  bg: string;
  icon: string;
  xp: number;
  desc: string;
  questions: QuizCentreQuestion[];
};

export const QUIZ_CENTRE: QuizCentreQuiz[] = [
  {
    id: 1,
    title: "Total Rewards Foundations",
    category: "Total Rewards Fundamentals",
    color: "#C8963E",
    bg: "#0C2340",
    icon: "◈",
    xp: 150,
    desc: "Master the five pillars of Total Rewards and the employee value proposition.",
    questions: [
      { q: "Which statement best describes Total Rewards?", opts: ["A payroll process focused only on salary payment dates.", "The full combination of financial and non-financial value employees receive from work.", "A benefits-only program managed by external vendors.", "A performance rating form used during annual reviews."], ans: 1, exp: "Total Rewards combines pay, benefits, wellbeing, recognition, career growth and work experience." },
      { q: "Which item is usually considered a non-cash reward?", opts: ["Annual base salary.", "Sales commission.", "Career development opportunity.", "Overtime payment."], ans: 2, exp: "Career development creates employee value without being a direct cash payment." },
      { q: "Why should Total Rewards align with business strategy?", opts: ["So reward investments support attraction, retention, performance and workforce priorities.", "So HR can avoid using data in reward decisions.", "So all employees receive identical rewards regardless of role or market.", "So benefits can replace salary structures."], ans: 0, exp: "Rewards should reinforce the talent and performance outcomes the business needs." },
      { q: "Which option best reflects a balanced Total Rewards approach?", opts: ["Increasing salaries while removing all employee support programs.", "Copying competitor benefits without checking workforce needs.", "Designing pay, benefits, wellbeing, recognition and growth programs around employee and business needs.", "Using job titles alone to decide all rewards."], ans: 2, exp: "A balanced approach considers multiple reward pillars and aligns them with strategy and workforce needs." },
      { q: "What is the Employee Value Proposition most closely connected to?", opts: ["The organization's complete promise of value to employees.", "The payroll tax schedule for each employee.", "The company's office seating arrangement.", "The legal name of the employer only."], ans: 0, exp: "The EVP explains why employees should join, stay and contribute, and Total Rewards makes that promise tangible." },
      { q: "Which reward pillar most directly supports employee health security?", opts: ["Job title architecture.", "Employee benefits.", "Office branding.", "Recruitment advertising."], ans: 1, exp: "Benefits such as health insurance, leave and life insurance help protect employees from risk." },
      { q: "Which is a common mistake in Total Rewards design?", opts: ["Reviewing employee needs before changing benefits.", "Using salary structures to support fair pay.", "Treating rewards as isolated programs instead of an integrated employee value system.", "Explaining rewards clearly to employees."], ans: 2, exp: "Rewards are stronger when compensation, benefits, wellbeing, recognition and career growth work together." },
      { q: "Which group would most likely value career development as part of Total Rewards?", opts: ["Only employees who do not receive base pay.", "Only employees who are leaving the organization.", "Employees at all stages who want to build skills and progress.", "Only payroll administrators."], ans: 2, exp: "Career development can be valuable across employee groups, although needs differ by career stage." },
      { q: "Why is communication important in Total Rewards?", opts: ["It guarantees every employee will like every benefit.", "It helps employees understand the value and purpose of reward programs.", "It eliminates the need for governance.", "It replaces market benchmarking."], ans: 1, exp: "Even well-designed rewards can be undervalued if employees do not understand them." },
      { q: "Which statement is most accurate?", opts: ["Total Rewards is broader than compensation and benefits.", "Total Rewards means salary only.", "Total Rewards applies only to executives.", "Total Rewards excludes employee experience."], ans: 0, exp: "Compensation and benefits are key components, but Total Rewards also includes wellbeing, recognition, growth and work experience." },
    ],
  },
  {
    id: 2,
    title: "Compensation Basics",
    category: "Compensation Fundamentals",
    color: "#2E7D8C",
    bg: "#071C22",
    icon: "◉",
    xp: 150,
    desc: "Understand base pay, salary ranges, variable pay, and compensation governance.",
    questions: [
      { q: "What best describes compensation?", opts: ["All forms of direct financial reward provided for work performed.", "Only employee wellness programs.", "Only company culture initiatives.", "Only unpaid recognition messages."], ans: 0, exp: "Compensation includes base pay, allowances, bonuses, commissions and other financial rewards." },
      { q: "Which item is an example of variable pay?", opts: ["Fixed monthly salary.", "A performance bonus linked to business results.", "Annual leave entitlement.", "Health insurance coverage."], ans: 1, exp: "Variable pay changes based on performance, results or defined targets." },
      { q: "What is a salary range?", opts: ["The total number of employees in a department.", "A benefits enrollment schedule.", "A minimum, midpoint and maximum pay framework for a role or grade.", "A list of payroll deductions."], ans: 2, exp: "Salary ranges define pay boundaries and target positioning for jobs or grades." },
      { q: "What does the salary midpoint usually represent?", opts: ["The minimum salary an employee can ever earn.", "The target market or fully competent pay point for the grade.", "The total company payroll budget.", "The maximum bonus opportunity."], ans: 1, exp: "Midpoint is commonly used as the reference rate for a fully competent employee." },
      { q: "What is pay compression?", opts: ["When all benefits are paid in cash.", "When salary grades are too wide to manage.", "When pay differences between new and experienced employees become too small.", "When payroll is processed earlier than usual."], ans: 2, exp: "Compression often happens when new hire pay rises faster than pay for existing employees." },
      { q: "Which factor should normally influence compensation decisions?", opts: ["Role responsibilities, market value, performance, skills and affordability.", "The employee's ability to negotiate alone.", "The department with the loudest manager.", "The oldest job title in the organization."], ans: 0, exp: "Sound compensation decisions consider multiple legitimate business and people factors." },
      { q: "What is total cash compensation?", opts: ["Base salary plus cash incentives or bonuses.", "Only non-cash benefits.", "Only retirement contributions.", "Only employer-provided learning programs."], ans: 0, exp: "Total cash usually includes fixed cash pay plus variable cash pay." },
      { q: "Which situation could create internal equity concerns?", opts: ["Two similar roles are placed in the same grade after evaluation.", "A new hire is paid much more than experienced peers without a clear reason.", "Salary ranges are reviewed using market data.", "Managers receive pay communication training."], ans: 1, exp: "Large unexplained pay differences among comparable employees may create equity concerns." },
      { q: "What is one purpose of compensation governance?", opts: ["To remove all manager involvement in pay discussions.", "To make pay decisions slower without reason.", "To create consistent rules for offers, increases, promotions and exceptions.", "To prevent HR from using salary data."], ans: 2, exp: "Governance improves consistency, fairness and budget discipline." },
      { q: "Which statement is accurate?", opts: ["Base pay is fixed compensation, while incentives are usually variable.", "Base pay is always optional.", "Incentives should never have measures.", "Compensation excludes cash payments."], ans: 0, exp: "Base pay is fixed; incentives depend on performance, results or targets." },
    ],
  },
  {
    id: 3,
    title: "Benefits Basics",
    category: "Benefits Management",
    color: "#3A7D44",
    bg: "#071A0C",
    icon: "◧",
    xp: 150,
    desc: "Learn employee benefits design, utilization, enrollment and communication.",
    questions: [
      { q: "What best describes employee benefits?", opts: ["Indirect rewards that support employee security, wellbeing or quality of life.", "Only salary increases paid once a year.", "Only job evaluation scores.", "Only sales incentive formulas."], ans: 0, exp: "Benefits include programs like health cover, retirement, leave, insurance and wellness support." },
      { q: "Which benefit most directly supports long-term financial security?", opts: ["Office parking allocation.", "Retirement or pension plan.", "Job title change.", "Performance appraisal form."], ans: 1, exp: "Retirement and pension benefits help employees prepare for future financial needs." },
      { q: "What should a benefits strategy balance?", opts: ["Employee preferences only.", "Vendor preferences only.", "Employee needs, market practice, affordability and business priorities.", "The number of pages in a policy document."], ans: 2, exp: "Effective benefits strategy balances workforce value, competitiveness and sustainable cost." },
      { q: "Why might employees undervalue a benefits program?", opts: ["They fully understand how to use it.", "They have clear benefit statements.", "They receive frequent communication.", "They do not understand the coverage, cost or value."], ans: 3, exp: "Poor communication often causes employees to overlook valuable benefits." },
      { q: "What is benefit utilization?", opts: ["How much or how often eligible employees use a benefit.", "The salary midpoint for a pay grade.", "The number of open jobs in a department.", "The annual performance rating scale."], ans: 0, exp: "Utilization helps HR understand whether a benefit is being used and valued." },
      { q: "Which is a common benefits governance question?", opts: ["What font should the company logo use?", "Who is eligible and what costs are shared by employer and employee?", "How many job titles should exist?", "What is the market salary percentile?"], ans: 1, exp: "Eligibility, cost sharing, vendor management and plan rules are core benefits governance issues." },
      { q: "What is a practical goal of benefits enrollment communication?", opts: ["To help employees make informed choices before deadlines.", "To discourage employees from using benefits.", "To hide eligibility rules.", "To replace all HR policies."], ans: 0, exp: "Enrollment communication should make choices, deadlines and actions clear." },
      { q: "Which program is commonly linked to employee wellbeing?", opts: ["Salary grade midpoint.", "Market pricing survey.", "Employee assistance or mental health support.", "Job evaluation committee score."], ans: 2, exp: "Employee assistance and mental health resources support wellbeing." },
      { q: "Why should benefits be reviewed periodically?", opts: ["Employee needs, vendor performance, costs and market practices can change.", "Benefits should remain unchanged forever.", "Reviewing benefits reduces all costs automatically.", "Only compensation programs require review."], ans: 0, exp: "Regular review keeps benefits relevant, competitive and sustainable." },
      { q: "Which statement is most accurate?", opts: ["Benefits are not part of Total Rewards.", "Benefits can support attraction, retention and wellbeing when well designed.", "Benefits should never be communicated to employees.", "Benefits are always more important than base pay."], ans: 1, exp: "Benefits are a core part of Total Rewards and can strengthen the employee value proposition." },
    ],
  },
  {
    id: 4,
    title: "Salary Structures",
    category: "Salary Structure Design",
    color: "#6B4C9A",
    bg: "#100818",
    icon: "◎",
    xp: 150,
    desc: "Build knowledge of grades, ranges, spread, governance and pay progression.",
    questions: [
      { q: "What is the main purpose of a salary structure?", opts: ["To organize pay decisions using grades, ranges and rules.", "To replace all benefits programs.", "To decide employee performance ratings.", "To remove the need for job descriptions."], ans: 0, exp: "Salary structures support consistent and fair pay decisions." },
      { q: "Which elements are normally found in a salary range?", opts: ["Bonus, leave and pension.", "Minimum, midpoint and maximum.", "Tax code, bank name and employee ID.", "Job title, manager name and department only."], ans: 1, exp: "The three core range points are minimum, midpoint and maximum." },
      { q: "What does range spread measure?", opts: ["The number of employees in a salary grade.", "The distance between two departments.", "The width of the salary range from minimum to maximum.", "The number of job descriptions created."], ans: 2, exp: "Range spread shows how wide a pay range is." },
      { q: "An employee paid below the range minimum should usually be:", opts: ["Automatically promoted without review.", "Ignored until the next job evaluation cycle.", "Moved to a different benefit plan.", "Reviewed for possible adjustment, data accuracy and role fit."], ans: 3, exp: "Below-range pay should be reviewed carefully to understand whether correction is needed." },
      { q: "Which statement best describes a salary grade?", opts: ["A grouping of roles with similar internal value or level.", "A list of employee benefit vendors.", "A payroll tax category only.", "A manager's personal pay preference."], ans: 0, exp: "Grades group jobs of similar value, scope or level." },
      { q: "Why are salary structures reviewed over time?", opts: ["Because jobs, markets and business needs change.", "Because salary ranges should be random.", "Because pay governance becomes unnecessary.", "Because employee names change."], ans: 0, exp: "Outdated ranges can weaken competitiveness and fairness." },
      { q: "What is range penetration used to understand?", opts: ["How far an employee's pay has moved through the salary range.", "How many benefits an employee selected.", "How many candidates applied for a role.", "How long a course takes to complete."], ans: 0, exp: "Range penetration measures salary position between minimum and maximum." },
      { q: "Which situation suggests possible pay progression concern?", opts: ["A new employee starts near minimum.", "A fully experienced strong performer remains far below midpoint for years without explanation.", "A salary structure has documented ranges.", "A grade has a defined midpoint."], ans: 1, exp: "Long-term position far below midpoint may require review, especially for experienced strong performers." },
      { q: "Which is a good salary structure governance practice?", opts: ["Allowing every manager to create private pay ranges.", "Ignoring market movement.", "Defining approval rules for offers, promotions and exceptions.", "Removing documentation from pay decisions."], ans: 2, exp: "Approval rules support consistency and control." },
      { q: "What can happen when salary ranges are poorly managed?", opts: ["Pay inequity, compression and budget inconsistency.", "Automatic improvement in employee trust.", "No need for salary review.", "Perfect market competitiveness."], ans: 0, exp: "Weak range governance can create fairness, competitiveness and cost issues." },
    ],
  },
  {
    id: 5,
    title: "Pay Equity",
    category: "Pay Equity",
    color: "#B84B4B",
    bg: "#1C0808",
    icon: "◈",
    xp: 150,
    desc: "Understand fairness, data analysis, governance and how to close pay gaps.",
    questions: [
      { q: "What does pay equity mean?", opts: ["Everyone must always earn exactly the same amount.", "Pay differences should be fair, explainable and based on legitimate factors.", "Employees should not know anything about pay.", "Only executives need pay review."], ans: 1, exp: "Pay equity allows legitimate differences but challenges unfair or unexplained gaps." },
      { q: "Which factor may legitimately explain pay differences?", opts: ["Manager favoritism.", "Personal negotiation pressure only.", "Relevant experience, skills, performance or role scope.", "Unrecorded historical habit."], ans: 2, exp: "Pay differences should be tied to relevant job or employee factors." },
      { q: "What is a common source of pay inequity?", opts: ["Inconsistent starting offers without internal equity checks.", "Documented salary structures.", "Clear promotion guidelines.", "Regular pay audits."], ans: 0, exp: "Uncontrolled offers can create gaps that grow over time." },
      { q: "Which data is useful for a basic pay equity review?", opts: ["Only office location and email address.", "Only employee hobbies.", "Only company logo data.", "Job, grade, salary, location, tenure, performance and relevant demographics where legally appropriate."], ans: 3, exp: "Pay equity analysis depends on clean job, pay and workforce data." },
      { q: "Why should pay equity analysis be handled carefully?", opts: ["It involves sensitive employee and compensation information.", "It does not require data privacy.", "It should be shared casually across the company.", "It replaces all compensation governance."], ans: 0, exp: "Pay equity work involves confidential data and should follow legal and ethical standards." },
      { q: "Which action helps prevent future inequity?", opts: ["Clear salary ranges, hiring guidelines and approval controls.", "Unlimited exceptions with no documentation.", "Allowing pay decisions based only on negotiation.", "Avoiding pay audits completely."], ans: 0, exp: "Governance reduces inconsistent decisions and unmanaged exceptions." },
      { q: "What does an unexplained pay gap indicate?", opts: ["Proof of illegal discrimination in every case.", "Nothing worth reviewing.", "A potential issue requiring deeper analysis.", "A reason to delete salary ranges."], ans: 2, exp: "A gap is a signal for further review, not an automatic conclusion." },
      { q: "How can pay transparency increase pressure on pay equity?", opts: ["Employees may compare ranges and ask for explanations of differences.", "It eliminates all pay questions.", "It makes salary structures irrelevant.", "It removes the need for manager training."], ans: 0, exp: "Transparent information often increases the need for clear, fair and explainable pay systems." },
      { q: "Which is the best beginner pay equity starting point?", opts: ["Ignore all historical salary decisions.", "Compare employees in similar roles or grades and investigate unusual gaps.", "Publish all salaries without analysis.", "Stop using salary data."], ans: 1, exp: "Peer comparisons within similar work groups are a practical starting point." },
      { q: "Which statement is most accurate?", opts: ["Pay equity is only about compliance, not trust.", "Pay equity supports fairness, trust and better reward governance.", "Pay equity means removing all performance-based pay.", "Pay equity is unrelated to Total Rewards."], ans: 1, exp: "Fair and explainable pay supports both compliance and employee trust." },
    ],
  },
  {
    id: 6,
    title: "Job Evaluation",
    category: "Job Evaluation",
    color: "#C8963E",
    bg: "#1A1000",
    icon: "◉",
    xp: 150,
    desc: "Evaluate roles fairly using point-factor methods, job families, and governance.",
    questions: [
      { q: "What does job evaluation assess?", opts: ["The relative value of a job, not the personal worth of the employee.", "Only an employee's performance rating.", "Only the employee's length of service.", "Only the market salary survey title."], ans: 0, exp: "Job evaluation focuses on role content, accountability, complexity and impact." },
      { q: "Which document is most useful before evaluating a job?", opts: ["A benefits invoice.", "A current job description.", "A payroll calendar.", "A recognition certificate."], ans: 1, exp: "A job description provides the duties, responsibilities and context needed for evaluation." },
      { q: "Which is a typical job evaluation factor?", opts: ["Preferred office color.", "Employee social media activity.", "Problem-solving or accountability.", "Personal negotiation style."], ans: 2, exp: "Common factors include knowledge, problem-solving, accountability, impact and working conditions." },
      { q: "Why should job evaluation decisions be documented?", opts: ["To support consistency, transparency and future review.", "To make job levels random.", "To hide grading logic from HR.", "To avoid salary structure design."], ans: 0, exp: "Documentation helps explain and defend grade decisions." },
      { q: "Which statement is most accurate?", opts: ["Job evaluation replaces performance management.", "Job evaluation evaluates role size; performance management evaluates employee contribution.", "Job evaluation is only for payroll processing.", "Job evaluation should be based only on job title."], ans: 1, exp: "The two processes are related but distinct." },
      { q: "What risk comes from relying only on job titles?", opts: ["Titles always describe work accurately.", "Different organizations or departments may use titles inconsistently.", "Job titles eliminate the need for evaluation.", "Titles automatically reflect market pay."], ans: 1, exp: "Titles can be misleading; role content matters more." },
      { q: "A point-factor method typically uses:", opts: ["Defined factors, levels and scoring.", "Only manager preference.", "Only employee age.", "Only benefits cost."], ans: 0, exp: "Point-factor systems score jobs against defined compensable factors." },
      { q: "Who should ideally participate in job evaluation governance?", opts: ["Only the employee being evaluated.", "Only payroll staff with no role information.", "Trained HR/rewards professionals and relevant business stakeholders.", "Only external candidates."], ans: 2, exp: "Evaluation benefits from trained reviewers and informed stakeholders." },
      { q: "Which outcome can job evaluation support?", opts: ["Fair grading and salary structure alignment.", "Automatic bonus payout.", "Benefits enrollment only.", "Employee tax filing."], ans: 0, exp: "Job evaluation helps map roles into levels and pay grades." },
      { q: "When should a role be considered for re-evaluation?", opts: ["When responsibilities, scope or accountability change significantly.", "Whenever an employee wants a higher title.", "Only when the company changes its logo.", "Never after initial evaluation."], ans: 0, exp: "Significant role changes may affect job level and grade." },
    ],
  },
  {
    id: 7,
    title: "Market Pricing",
    category: "Market Pay",
    color: "#0E8A82",
    bg: "#071A18",
    icon: "◧",
    xp: 150,
    desc: "Use salary surveys, percentiles, and job matching to benchmark competitively.",
    questions: [
      { q: "What is market pricing?", opts: ["Comparing jobs to external pay data for similar work.", "Setting all salaries based on employee preference.", "Replacing job evaluation with job titles only.", "Calculating only payroll taxes."], ans: 0, exp: "Market pricing helps organizations understand external pay competitiveness." },
      { q: "What is the most important principle in job matching?", opts: ["Match by title only.", "Match by responsibilities, scope and level.", "Match by employee name.", "Match by office location only."], ans: 1, exp: "Job content is more reliable than title alone." },
      { q: "What does the 50th percentile usually represent?", opts: ["The highest pay in the market.", "The lowest pay in the market.", "The market median.", "The company's total payroll cost."], ans: 2, exp: "The 50th percentile is the median point of the market data." },
      { q: "Which issue can weaken market pricing quality?", opts: ["Using reliable survey data.", "Documenting job matches.", "Reviewing relevant labor markets.", "Matching jobs poorly or using outdated data."], ans: 3, exp: "Poor matches and stale data can lead to incorrect pay conclusions." },
      { q: "Why is external competitiveness important?", opts: ["It helps attract and retain talent in relevant labor markets.", "It means internal fairness no longer matters.", "It requires paying every job above market.", "It eliminates salary budgeting."], ans: 0, exp: "Competitive pay helps organizations compete for talent." },
      { q: "Which is a good market pricing practice?", opts: ["Use multiple relevant data sources where possible.", "Use employee rumors as the main data source.", "Ignore location and industry differences.", "Benchmark only by job title."], ans: 0, exp: "Multiple relevant sources can improve confidence in market conclusions." },
      { q: "What is market positioning strategy?", opts: ["Choosing a target pay position such as median or above median.", "Choosing office seating order.", "Choosing employee ID numbers.", "Choosing the font for salary letters."], ans: 0, exp: "Organizations may target a percentile based on talent strategy and affordability." },
      { q: "Which statement is most accurate?", opts: ["Market pricing should be balanced with internal equity.", "Market pricing always overrides fairness concerns.", "Market pricing is unrelated to salary ranges.", "Market pricing works without job data."], ans: 0, exp: "Pay decisions should consider both market competitiveness and internal fairness." },
      { q: "Why might a company target above the market median for some roles?", opts: ["The role may be critical, scarce or difficult to hire.", "The role has no business value.", "The company wants to avoid all pay governance.", "Market data is never relevant."], ans: 0, exp: "Critical or scarce roles may justify a stronger market position." },
      { q: "What should HR check when a new hire requires a high market offer?", opts: ["Whether internal compression or equity issues may be created.", "Whether job descriptions should be deleted.", "Whether benefits enrollment should stop.", "Whether all salaries should become identical."], ans: 0, exp: "High offers can create internal pay pressure if not managed carefully." },
    ],
  },
  {
    id: 8,
    title: "Incentives & Variable Pay",
    category: "Variable Pay",
    color: "#B84B4B",
    bg: "#1C0808",
    icon: "◎",
    xp: 150,
    desc: "Design effective incentive plans with clear measures, thresholds and governance.",
    questions: [
      { q: "What is variable pay?", opts: ["Compensation that varies based on performance, results or defined conditions.", "A fixed salary that never changes.", "Only employer-paid health insurance.", "A job evaluation score."], ans: 0, exp: "Variable pay is linked to outcomes, performance or targets." },
      { q: "Which plan is most likely a sales incentive?", opts: ["Annual leave policy.", "Commission based on sales results.", "Retirement contribution schedule.", "Job grading framework."], ans: 1, exp: "Sales commissions reward sales performance or revenue generation." },
      { q: "What does line of sight mean in incentive design?", opts: ["Employees understand and can influence the measured results.", "Employees can see the payroll office.", "The incentive formula is hidden.", "Only executives can participate."], ans: 0, exp: "Incentives work better when employees see how their actions affect outcomes." },
      { q: "Which feature should an incentive plan clearly define?", opts: ["Eligibility, measures, targets, payout formula and timing.", "Employee lunch preferences.", "Office decoration standards.", "Personal social media accounts."], ans: 0, exp: "Clear rules reduce confusion and disputes." },
      { q: "Which is a risk of poorly designed incentives?", opts: ["They may encourage unintended behavior or narrow focus.", "They always improve collaboration.", "They remove all cost concerns.", "They eliminate the need for performance measures."], ans: 0, exp: "Incentives can backfire if measures are too narrow or poorly aligned." },
      { q: "What is a performance threshold?", opts: ["The minimum performance level required before payout begins.", "The maximum number of employees in a department.", "The salary midpoint of a grade.", "The date benefits enrollment opens."], ans: 0, exp: "Thresholds define the minimum result needed for incentive eligibility or payout." },
      { q: "Which measure would be most relevant for a customer service incentive?", opts: ["Customer satisfaction or service quality scores.", "Employee shoe size.", "Office wall color.", "Payroll bank name."], ans: 0, exp: "Measures should align with the role's intended outcomes." },
      { q: "Why should incentives be affordable?", opts: ["Payout promises must be financially sustainable.", "Employees should never receive payouts.", "Budgets are unrelated to incentives.", "Affordability only matters for benefits."], ans: 0, exp: "An incentive plan loses credibility if the organization cannot fund earned payouts." },
      { q: "Which statement is most accurate?", opts: ["A good incentive plan is clear, measurable, aligned and governed.", "A good incentive plan is vague and secret.", "A good incentive plan ignores business goals.", "A good incentive plan pays randomly."], ans: 0, exp: "Clarity, measurable goals and governance are central to effective incentives." },
      { q: "Which incentive design question should HR ask first?", opts: ["What behavior or outcome should this plan encourage?", "How can we avoid explaining the plan?", "How can we make every payout identical?", "How can we remove all performance measures?"], ans: 0, exp: "Purpose should drive plan design." },
    ],
  },
  {
    id: 9,
    title: "Rewards Communication",
    category: "Rewards Communication",
    color: "#3A7D44",
    bg: "#071A0C",
    icon: "◈",
    xp: 150,
    desc: "Communicate pay, benefits and Total Rewards clearly across the employee lifecycle.",
    questions: [
      { q: "Why is rewards communication important?", opts: ["It helps employees understand the purpose, value and rules of reward programs.", "It replaces fair pay design.", "It removes the need for benefits administration.", "It guarantees no employee will question pay."], ans: 0, exp: "Clear communication improves understanding and trust." },
      { q: "What is a total rewards statement?", opts: ["A list of company slogans.", "A summary of the value of pay, benefits and other rewards.", "A manager-only performance rating form.", "A payroll tax exemption."], ans: 1, exp: "Total rewards statements show employees the broader value of their rewards package." },
      { q: "Which communication style is best for explaining benefits to employees?", opts: ["Technical language only.", "Long policy text without examples.", "Clear, practical language with examples and actions.", "No communication unless employees complain."], ans: 2, exp: "Simple explanations and examples help employees make informed choices." },
      { q: "Why should managers be trained in reward communication?", opts: ["They often answer employee questions about pay and benefits.", "They should create separate salary structures for each team.", "They should replace HR governance.", "They should promise pay increases without approval."], ans: 0, exp: "Managers need consistent guidance for sensitive pay and benefits conversations." },
      { q: "Which message is most useful during benefits enrollment?", opts: ["A vague reminder with no deadline.", "A clear explanation of choices, eligibility, deadlines and support contacts.", "A salary survey extract only.", "A job evaluation scorecard only."], ans: 1, exp: "Enrollment messages should help employees act correctly and on time." },
      { q: "What is one risk of poor rewards communication?", opts: ["Employees may undervalue or misunderstand programs.", "Employees automatically appreciate every reward.", "Pay equity improves without analysis.", "Benefits costs disappear."], ans: 0, exp: "Lack of understanding can reduce perceived value and trust." },
      { q: "Which communication channel can be useful for explaining complex rewards topics?", opts: ["Only legal policy documents.", "Only one short email per year.", "A mix of FAQs, webinars, manager guides, infographics and employee statements.", "No communication channel is needed."], ans: 2, exp: "Multiple channels support different learning preferences and complexity levels." },
      { q: "Which statement should HR avoid?", opts: ["Explaining how salary ranges work.", "Using clear examples of benefit value.", "Training managers before pay conversations.", "Making promises about pay outcomes that are not approved or funded."], ans: 3, exp: "Unapproved promises damage trust and create risk." },
      { q: "What does good rewards communication support?", opts: ["Trust, understanding and better employee decisions.", "Secrecy, confusion and inconsistent messages.", "The removal of salary governance.", "The replacement of HR analytics."], ans: 0, exp: "Communication helps employees understand what exists, why it exists and how to use it." },
      { q: "When should rewards communication happen?", opts: ["Only after employees resign.", "Across the employee lifecycle, including hiring, onboarding, review and enrollment moments.", "Only when payroll errors occur.", "Never during performance review periods."], ans: 1, exp: "Rewards messages are most effective when repeated at relevant moments." },
    ],
  },
  {
    id: 10,
    title: "Career Readiness",
    category: "Total Rewards Career",
    color: "#2E7D8C",
    bg: "#071C22",
    icon: "◉",
    xp: 150,
    desc: "Test your readiness to work in Total Rewards with scenario-based career questions.",
    questions: [
      { q: "Which skill is especially important for a rewards analyst?", opts: ["Data analysis and spreadsheet confidence.", "Avoiding numbers completely.", "Ignoring employee questions.", "Using job titles as the only evidence."], ans: 0, exp: "Rewards analysts work with pay data, surveys, budgets and workforce information." },
      { q: "Why is business acumen important in Total Rewards?", opts: ["Rewards decisions affect cost, talent, performance and competitiveness.", "It replaces ethics.", "It removes the need for data.", "It makes benefits communication unnecessary."], ans: 0, exp: "Rewards professionals must connect people programs to business priorities." },
      { q: "Which portfolio item would help an aspiring rewards professional?", opts: ["A sample salary structure with compa-ratio analysis.", "A list of unrelated hobbies only.", "A confidential employee salary file copied from work.", "A company logo redesign only."], ans: 0, exp: "A practical, anonymized portfolio shows applied compensation capability." },
      { q: "Why is confidentiality essential in Total Rewards?", opts: ["Rewards professionals handle sensitive pay, performance and employee data.", "All salary data should be shared casually.", "Confidentiality prevents fair analysis.", "Only finance needs confidentiality."], ans: 0, exp: "Sensitive reward information must be handled ethically and securely." },
      { q: "Which learning path is most useful for a beginner?", opts: ["Start with salary structures, benefits, job evaluation, market pricing and pay equity basics.", "Start by designing executive plans without fundamentals.", "Avoid compensation terms until becoming a manager.", "Focus only on office administration."], ans: 0, exp: "A strong foundation prepares learners for more advanced rewards work." },
      { q: "What makes Total Rewards a strategic HR field?", opts: ["It connects employee value, business cost, performance and talent strategy.", "It only processes payroll files.", "It excludes analytics.", "It does not require stakeholder management."], ans: 0, exp: "Total Rewards influences workforce behavior, cost and competitiveness." },
      { q: "Which behavior shows career readiness in rewards?", opts: ["Asking how pay decisions are governed and supported by data.", "Relying only on rumors about salaries.", "Avoiding all policy documents.", "Making pay promises without authority."], ans: 0, exp: "Curiosity about governance and data signals professional maturity." },
      { q: "Why should rewards professionals keep learning?", opts: ["Markets, laws, technology and employee expectations change.", "Total Rewards never changes.", "Salary data is permanent.", "Benefits are identical in every country."], ans: 0, exp: "Continuous learning is essential in a changing rewards environment." },
      { q: "Which combination best describes a future-ready rewards professional?", opts: ["Data, empathy, communication, ethics and business judgment.", "Secrecy, guesswork and inconsistent decisions.", "Only technical formulas without people understanding.", "Only employee relations knowledge with no data skills."], ans: 0, exp: "The future rewards role combines analytical and human-centered capability." },
      { q: "What is a good first step for an HR generalist moving into Total Rewards?", opts: ["Volunteer for salary review, benefits communication or job description projects.", "Wait until becoming an executive.", "Avoid Excel and analytics.", "Study only recruitment marketing."], ans: 0, exp: "Project exposure helps build practical rewards experience." },
    ],
  },
];
